<div class="about">
    <div class="custom-heading">
        <h2>
            <span class="green-letter" data-text="F">F</span>
            <span class="green-letter" data-text="A">a</span>
            <span class="green-letter" data-text="S">s</span>
            <span class="green-letter" data-text="T">t</span>
            <span class="blue-letter" data-text="C">C</span>
            <span class="blue-letter" data-text="V">V</span>
        </h2>
    </div>

    <section class="section-photos">
        <h3>À propos de</h3>
        <div class="gallery">
            <ul>
                <li>
                    <a href="#section1">
                        <img src="public/img/mission.jpg" alt="Image illustrant notre mission">
                        <div class="overlay">
                            <h4>Notre Mission</h4>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#section2">
                        <img src="public/img/histoire.jpg" alt="Image illustrant notre histoire">
                        <div class="overlay">
                            <h4>Notre Histoire</h4>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#section3">
                        <img src="public/img/valeurs.jpg" alt="Image illustrant nos valeurs">
                        <div class="overlay">
                            <h4>Nos Valeurs</h4>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#section4">
                        <img src="public/img/equipe.jpg" alt="Image illustrant notre équipe">
                        <div class="overlay">
                            <h4>L'Équipe FastCV</h4>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#section5">
                        <img src="public/img/engagement.jpg" alt="Image illustrant notre engagement">
                        <div class="overlay">
                            <h4>Engagement envers les Utilisateurs</h4>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#section6">
                        <img src="public/img/eco.jpg" alt="Image illustrant notre investissement à l'écologie">
                        <div class="overlay">
                            <h4>L'Éco-confection</h4>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#section7">
                        <img src="public/img/cv.jpg" alt="Image illustrant la création de CVs">
                        <div class="overlay">
                            <h4>L'Art du CV</h4>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#section8">
                        <img src="public/img/protect.jpg" alt="Image illustrant la protection informatique">
                        <div class="overlay">
                            <h4>Protection des Données</h4>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
    </section>

    <section>
        <article class="about-text">
            <div class="spacing">
                <p><strong>FastCV est bien plus qu'un simple outil de création de CV.</strong></p>
                <p><strong>Nous sommes une équipe de passionnés de la carrière et du développement web dédiée à vous aider à atteindre vos objectifs professionnels.</strong></p>
            </div>
        </article>
    </section>

    <section id="section1">
        <article class="about-text">
            <div class="spacing">
                <span class="emoji">🌟</span>
                <h3>Notre Mission :</h3>
                <p>Notre mission est de simplifier le processus de création de CV pour vous permettre de briller dans votre carrière. Nous croyons que chaque professionnel mérite un CV de qualité professionnelle qui reflète son parcours unique. 📄</p>
            </div>
        </article>
    </section>

    <section id="section2">
        <article class="about-text">
            <div class="spacing">
                <span class="emoji">🌐</span>
                <h3>Notre Histoire :</h3>
                <p>FastCV a été fondé par une équipe de développeurs full stack qui, après avoir travaillé dans diverses industries, ont réalisé à quel point la création de CV pouvait être fastidieuse.</p>
                <p>Notre passion pour la simplification de ce processus a donné naissance à FastCV.</p>
            </div>
        </article>
    </section>

    <section id="section3">
        <article class="about-text">
            <div class="spacing">
                <span class="emoji">🤝</span>
                <h3>Nos Valeurs :</h3>
                <p>Chez FastCV, nous nous engageons envers la simplicité, la qualité et la satisfaction de l'utilisateur.</p>
                <p>Chaque fonctionnalité de notre service est conçue pour vous offrir la meilleure expérience possible.</p>
            </div>
        </article>
    </section>

    <section id="section4">
        <article class="about-text">
            <div class="spacing">
                <span class="emoji">👩‍💻</span>
                <h3>L'Équipe FastCV :</h3>
                <p>Notre équipe est composée de développeurs, de designers et d'experts en recrutement dévoués à créer un outil exceptionnel.</p>
                <p>Nous mettons notre expertise au service de votre succès professionnel. 🛠️</p>
            </div>
        </article>
    </section>

    <section id="section5">
        <article class="about-text">
            <div class="spacing">
                <span class="emoji">💬</span>
                <h3>Engagement envers les Utilisateurs :</h3>
                <p>Votre succès est notre priorité. Nous écoutons attentivement les commentaires de nos utilisateurs et apportons constamment des améliorations pour répondre à vos besoins.</p>
            </div>
        </article>
    </section>

    <section id="section6">
        <article class="about-text">
            <div class="spacing">
                <span class="emoji">🌍</span>
                <h3>L'Éco-confection :</h3>
                <p>Chez FastCV, nous sommes fiers d'adopter des pratiques éco-responsables dans notre développement et notre fonctionnement.</p>
                <p>Nous minimisons notre empreinte carbone en utilisant des serveurs alimentés par des énergies renouvelables et en favorisant le travail à distance.</p>
            </div>
        </article>
    </section>

    <section id="section7">
        <article class="about-text">
            <div class="spacing">
                <span class="emoji">🎨</span>
                <h3>L'Art du CV :</h3>
                <p> Découvrez notre section "<a href="index.php?route=good-cv">L'Art du CV</a>" où nous partageons des conseils et des astuces pour créer un CV qui vous démarque.</p>
                <p>Explorez les dernières tendances en matière de CV et apprenez à optimiser chaque section pour impressionner les recruteurs.</p>
            </div>
        </article>
    </section>

    <section id="section8">
        <article class="about-text">
            <div class="spacing">
                <span class="emoji">🔐</span>
                <h3>Protection des Données :</h3>
                <p>Chez FastCV, nous prenons la sécurité et la confidentialité de vos données très au sérieux.</p>
                <p>Consultez notre "<a href="index.php?route=politique">Politique de Confidentialité</a>" pour en savoir plus sur la manière dont nous protégeons vos informations personnelles.</p>
            </div>
        </article>
    </section>

    <section>
        <article class="about-text">
            <div class="spacing">
                <p><strong>Rejoignez des milliers d'utilisateurs satisfaits et créez le CV qui vous ouvrira de nouvelles opportunités professionnelles.</strong></p>
                <p><strong>FastCV est là pour vous aider à atteindre vos objectifs de carrière.</strong></p>
            </div>
        </article>
    </section>
</div>