<div id="cookie-consent-popup" class="centered-popup hidden-popup">
    <div class="popup-content">
        <p>Nous utilisons des cookies <b>uniquement</b> dans le but d'améliorer votre expérience sur notre site. </p>
        <p>Vous pouvez consulter notre <a href="http://localhost/FastCV/views/politique.phtml">Politique de confidentialité</a>
        </p>
        <button id="accept-cookies">Accepter</button>
        <button id="refuse-cookies">Refuser</button>
    </div>
</div>