<footer class="site-footer">
    <div class="footer-content">
        <div class="footer-logo">
            <a href="index.php"><img src="public/img/logo.png" alt="Logo FastCV" class="rotate-on-hover"></a>
        </div>
        <div class="footer-links">
                <div class="footer-links-container">
                    <ul>
                        <li><a href="index.php?route=home" class="underline-on-hover">Accueil</a></li>
                        <li><a href="index.php?route=about" class="underline-on-hover">À propos</a></li>
                        <li><a href="index.php?route=good-cv" class="underline-on-hover">L'Art du CV</a></li>
                        <li><a href="index.php?route=politique" class="underline-on-hover">Politique de Confidentialité</li>
                        <li><a href="#" class="underline-on-hover">Contact</a></li>
                        <li><a href="#" class="underline-on-hover back-to-top">Haut de la page</a></li>
                    </ul>
                </div>
        </div>
        <div class="footer-social">
            <a href="https://linkedin.com/" target="_blank"><i class="fab fa-linkedin"></i></a>
            <a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook"></i></a>
            <a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i></a>
        </div>
        <p class="footer-text">© 2023 FastCV - Tous droits réservés</p>
    </div>
</footer>
