<header class="site-header">
    <div class="header-content">
        <div class="header-logo">
            <div class="logo-container">
                <a href="index.php">
                    <img src="public/img/logo.png" alt="Logo FastCV" class="rotate-on-hover" aria-label="Logo FastCV - Votre CV en quelques clics !">
                </a>
            </div>
        </div>
        <div class="header-title-description">
            <p class="rev-block">Bienvenue sur <strong class="strong-title">FastCV</strong></p>
            <p class="rev-block reverse">Créez votre <strong class="strong-title-cv">CV</strong> en quelques clics !</p>
        </div>
        <nav class="header-nav">
            <ul>
                <li><a href="index.php?route=home" <?php echo ($this->isPageActive('home')) ? 'class="active"' : ''; ?>>Accueil</a></li>
                <li><a href="index.php?route=about" <?php echo ($this->isPageActive('about')) ? 'class="active"' : ''; ?>>À propos</a></li>
                <li>
                    <?php if ($this->isLoggedIn) : ?>
                        <div class="column-list">
                            <span class="name-connect">Bonjour <?php echo htmlspecialchars($this->getUsername()); ?></span>
                            <a href="index.php?route=profile" <?php echo ($this->isPageActive('profile')) ? 'class="active"' : ''; ?>>Profil</a>
                            <a href="index.php?route=create-cv" <?php echo ($this->isPageActive('create-cv')) ? 'class="active"' : ''; ?>>Création de CV</a>
                            <a href="index.php?route=logout" class="disconnect">Se déconnecter</a>
                        </div>
                    <?php else : ?>
                <li><a href="index.php?route=login" <?php echo ($this->isPageActive('login')) ? 'class="active"' : ''; ?>>Connection</a></li>
            <?php endif; ?>
            </li>
            </ul>
        </nav>
    </div>
</header>