<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FastCV</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="public/css/design-tokens.css">
    <link rel="stylesheet" href="public/css/style.css">
<body>
    <?php include_once($this->template); ?>

    <?php include_once('cookie-consent-popup.phtml'); ?>

    <script src="public/js/script.js"></script>
    <script src="public/js/cookie-consent.js"></script>
</body>

</html>