<section class="login">
    <h2>Connexion</h2>
    <form class="input-container" action="index.php?route=login" method="POST">
        <input type="hidden" name="csrfToken" value="<?php echo $this->getCsrfToken(); ?>">
        <label for="username">Nom d'utilisateur :</label>
        <input type="text" name="username" id="username" required>
        <label for="password">Mot de passe :</label>
        <input type="password" name="password" id="password" required>
        <button type="button" id="toggleLoginPassword">👀</button>
        <br>
        <input type="submit" value="Se connecter">
    </form>

    <?php if ($this->getRegistrationSuccess()) : ?>
        <p class="success">Votre compte a été créé avec succès. Vous pouvez maintenant vous connecter.</p>
    <?php endif; ?>

    <?php if (!empty($this->errorMessage)) : ?>
        <p class="error"><?php echo $this->errorMessage; ?></p>
    <?php endif; ?>

    <p>Vous n'avez pas de compte ? <a href="index.php?route=register">Inscrivez-vous</a></p>
</section>