<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Politique de confidentialité - FastCV.fr</title>
    <link rel="stylesheet" href="../public/css/design-tokens.css">
    <link rel="stylesheet" href="../public/css/politique.css">
</head>

<body class="politique-confidentialite">
    <h1>Politique de confidentialité</h1>
    <div class="container-politique">
        <p>
        <h2>FastCV.fr</h2>
        </p>
        <p class="center"><strong>Type de site :</strong> Création de CV</p>

        <p class="center"><strong>Le but de cette politique de confidentialité</strong></p>
        <p>Le but de cette politique de confidentialité est d'informer les utilisateurs de notre site des données personnelles que nous recueillerons ainsi que les informations suivantes, le cas échéant :</p>

        <p class="center"><strong>Lois applicables</strong></p>
        <p>Les données à caractère personnel doivent être :</p>
        <ul>
            <li>traitées de manière licite, loyale et transparente au regard de la personne concernée (licéité, loyauté, transparence)</li>
            <li>collectées pour des finalités déterminées, explicites et légitimes, et ne pas être traitées ultérieurement d'un manière incompatible avec ces finalités</li>
            <li>exactes et, si nécessaire, tenues à jour</li>
            <li>conservées sous une forme permettant l'identification des personnes concernées pendant une durée n’excédant pas celle nécessaire au regard des finalités pour lesquelles elles sont traitées</li>
            <li>traitées de façon à garantir une sécurité appropriée des données à caractère personnel</li>
        </ul>

        <p class="center"><strong>Le traitement n'est licite que si, et dans la mesure où, au moins une des conditions suivantes est remplie :</strong></p>
        <ul>
            <li>la personne concernée a consenti au traitement de ses données à caractère personnel pour une ou plusieurs finalités spécifiques</li>
            <li>le traitement est nécessaire à l'exécution d'un contrat auquel la personne concernée est partie ou à l'exécution de mesures précontractuelles prises à la demande de celle-ci</li>
            <li>le traitement est nécessaire au respect d'une obligation légale à laquelle le responsable du traitement est soumis</li>
            <li>Le traitement est nécessaire à la sauvegarde des intérêts vitaux de la personne concernée ou d'une autre personne physique</li>
            <li>le traitement est nécessaire à l'exécution d'une mission d’intérêt public ou relevant de l'exercice de l'autorité publique dont est investi le responsable du traitement</li>
            <li>le traitement est nécessaire aux fins des intérêts légitimes poursuivis par le responsable du traitement ou par un tiers, à moins que ne prévalent les intérêts ou les libertés et droits fondamentaux de la personne concernée qui exigent une protection des données à caractère personnel, notamment lorsque la personne concernée est un enfant</li>
        </ul>

        <p>Pour les résidents de l’État de Californie, cette politique de confidentialité vise à se conformer à la California Consumer Privacy Act (CCPA). S'il y a des incohérences entre ce document et la CCPA, la législation de l’État s'appliquera. Si nous constatons des incohérences, nous modifierons notre politique pour nous conformer à la loi pertinente.</p>

        <p class="center"><strong>Consentement</strong></p>
        <p>Les utilisateurs conviennent qu'en utilisant notre site, ils consentent à :</p>
        <ul>
            <li>les conditions énoncées dans la présente politique de confidentialité et</li>
            <li>la collecte, l'utilisation et la conservation des données énumérées dans la présente politique.</li>
        </ul>

        <h3 class="center"><strong>Données personnelles que nous collectons</strong></h3>
        <p class="center"><strong>Données collectées</strong></p>
        <p>Nous pouvons également collecter les données suivantes lorsque vous effectuez certaines fonctions sur notre site :</p>
        <ul>
            <li>Prénom et nom</li>
            <li>Age</li>
            <li>Date de naissance</li>
            <li>Email</li>
            <li>Numéro de téléphone</li>
            <li>Domicile</li>
            <li>Données de remplissage automatique</li>
            <li>Renseignement sur l'expérience professionnelle</li>
        </ul>

        <p>Ces données peuvent être recueillies au moyen des méthodes suivantes :</p>
        <ul>
            <li>Enregistrement d'un compte</li>
        </ul>

        <p>Veuillez noter que nous ne collectons que les données qui nous aident à atteindre l'objectif énoncé dans cette politique de confidentialité. Nous ne recueillerons pas de données supplémentaires sans vous informer au préalable.</p>

        <p class="center"><strong>Comment nous utilisons les données personnelles</strong></p>
        <p>Les données personnelles recueillies sur notre site seront utilisées uniquement aux fins précisées dans la présente politique ou indiquées sur les pages pertinentes de notre site. Nous n'utiliserons pas vos données au-delà de ce que nous divulguerons.</p>

        <p>Les données que nous recueillons lorsque l'utilisateur exécute certaines fonctions peuvent être utilisées aux fins suivantes :</p>
        <ul>
            <li>Pour la création d'un compte</li>
            <li>Pour la création d'un CV</li>
        </ul>

        <h3 class="center"><strong>Avec qui nous partageons les données personnelles</strong></h3>
        <p class="center"><strong>Employés</strong></p>
        <p>Nous pouvons divulguer à tout membre de notre organisation les données utilisateur dont il a raisonnablement besoin pour réaliser les objectifs énoncés dans la présente politique.</p>

        <p class="center"><strong>Tierces parties</strong></p>
        <p>Nous ne partagerons pas les données utilisateur avec des tierces parties.</p>

        <p class="center"><strong>Autres divulgations</strong></p>
        <p>Nous nous engageons à ne pas vendre ou partager vos données avec des tiers, sauf dans les cas suivants :</p>
        <ul>
            <li>si la loi l'exige</li>
            <li>si elle est requise pour toute procédure judiciaire</li>
            <li>pour prouver ou protéger nos droits légaux</li>
            <li>à des acheteurs ou acheteurs potentiels de cette société dans le cas où nous cherchons à vendre la société</li>
        </ul>

        <p>Si vous suivez des hyperliens de notre site vers un autre site, veuillez noter que nous ne sommes pas responsables et n'avons pas de contrôle sur leurs politiques et pratiques de confidentialité.</p>

        <p class="center"><strong>Combien de temps nous stockons les données personnelles</strong></p>
        <p>Nous ne conservons pas les données des utilisateurs au-delà de ce qui est nécessaire pour atteindre les fins pour lesquelles elles sont recueillies.</p>

        <p class="center"><strong>Comment nous protégeons vos données personnelles</strong></p>
        <p>Toutes les données stockées dans notre système sont bien sécurisées et ne sont accessibles qu'à nos employés. Nos employés sont liés par des accords de confidentialité stricts et une violation de cet accord entraînerait le licenciement de l'employé.</p>

        <p>Alors que nous prenons toutes les précautions raisonnables pour nous assurer que nos données d'utilisateur sont sécurisées et que les utilisateurs sont protégés, il reste toujours du risque de préjudice. L'internet en sa totalité peut être, parfois, peu sûr et donc nous sommes incapables de garantir la sécurité des données des utilisateurs au-delà de ce qui est raisonnablement pratique.</p>

        <p class="center"><strong>Mineurs</strong></p>
        <p>Le RGPD précise que les personnes de moins de 15 ans sont considérées comme des mieux aux fins de la collecte des données. Les mineurs doivent avoir le consentement d'un représentant légal pour que leurs données soient recueillies, traitées et utilisées.</p>

        <p class="center"><strong>Vos droits en tant qu'utilisateur</strong></p>
        <p>En vertu du RGPD, les utilisateurs ont les droits suivants en tant que personnes concernées :</p>
        <ul>
            <li>droit d'accès</li>
            <li>droit de rectification</li>
            <li>droit à l'effacement</li>
            <li>droit de restreindre le traitement</li>
            <li>droit à la portabilité des données</li>
            <li>droit d'objection</li>
        </ul>

        <p>Vous trouverez de plus amples informations sur ces droits au chapitre 3 (art 12-23) du RGPD.</p>

        <p class="center"><strong>Comment modifier, supprimer ou contester les données recueillies</strong></p>
        <p>Si vous souhaitez que vos renseignements soient supprimés ou modifiés d'une façon ou d'une autre, veuillez communiquer avec notre agent de protection de la vie privée ici :</p>
        <p>Julien Le Goff</p>
        <p>19 rue Clément Marot, 29200, Brest</p>
        <p>ju.legoff29@gmail.com</p>
        <p>06 58 69 47 73</p>

        <p class="center"><strong>Politique sur les cookies</strong></p>
        <p>Un cookie est un petit fichier, stocké sur le disque dur d'un utilisateur par le site Web. Son but est de recueillir des données relatives aux habitudes de navigation de l'utilisateur.</p>

        <p>Nous utilisons le type de cookies suivant sur notre site :</p>
        <ul>
            <li>Cookies fonctionnels - Nous les utilisons pour mémoriser toutes les sélections que vous faites sur notre site afin qu'elles soient sauvegardées pour vos prochaines visites.</li>
        </ul>

        <p>Vous pouvez choisir d'être averti chaque fois qu'un cookie est transmis. Vous pouvez également choisir de désactiver les cookies entièrement dans votre navigateur internet, mais cela peut diminuer la qualité de votre expérience d’utilisation.</p>

        <p class="center"><strong>Modifications</strong></p>
        <p>Cette politique de confidentialité peut être modifiée à l'occasion afin de maintenir la conformité avec la loi et de tenir compte de tout changement à notre processus de collecte de données. Nous recommandons à nos utilisateurs de vérifier notre politique de temps à autre pour s'assurer qu'ils soient informés de toute mise à jour. Au besoin, nous pouvons informer les utilisateurs par courriel des changements apportés à cette politique.</p>

        <p class="center"><strong>Contact</strong></p>
        <p>Si vous avez des questions à poser, n'hésitez pas à communiquer avec nous en utilisant ce qui suit :</p>
        <p>ju.legoff29@gmail.com</p>
        <p class="center">Date d'entrée en vigueur le 17/11/2023</p>
    </div>
    <p class="center footer">© 2023, FastCV™ - Tous droits réservés.</p>
    <a href="http://localhost/FastCV/index.php?route=home" class="back-button">Retour à l'accueil</a>
    <div class="margin-footer"></div>
    <div class="margin-footer"></div>
</body>

</html>