<footer class="site-footer">
    <div class="footer-content">
        <div class="footer-logo">
            <a href="index.php"><img src="public/img/logo.png" alt="Logo FastCV" class="rotate-on-hover"></a>
        </div>
        <div class="footer-links">
            <ul>
                <li><a href="index.php?route=home" class="underline-on-hover">Accueil</a></li>
                <li><a href="index.php?route=about" class="underline-on-hover">À propos</a></li>
                <li><a href="http://localhost/FastCV/views/good-cv.phtml" class="underline-on-hover">L'Art du CV</a></li>
                <li><a href="http://localhost/FastCV/views/politique.phtml" class="underline-on-hover">Politique de Confidentialité</li>
                <li><a href="#" class="underline-on-hover">Contact</a></li>
                <li><a href="#" class="underline-on-hover">Haut de la page</a></li>
            </ul>
        </div>
        <div class="footer-social">
            <a href="#" target="_blank"><i class="fab fa-linkedin"></i></a>
            <a href="#" target="_blank"><i class="fab fa-facebook"></i></a>
            <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
        </div>
        <p>© 2023 FastCV - Tous droits réservés</p>
    </div>
</footer>
